### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by IcyW** [williamfzc/work_with_stagesepx#1]
P.s. 可能不是issue，算是请问一下。

前置步骤，auto/start_without_report.py原始脚本的运行很顺利，不过我尝试改`cl.load("xxx") `中的图片分类后，通过`filter(lambda x: x.stage != '-3', classify_result.data)`将非关键帧剔除，并创建新的`key_result = ClassifierResult(data=list(key_result_list))`

但是接下来想将剩余的数据进行to_dict()和draw()操作时，都会在`stagesepx/classifier/base.py", line 149, in get_stage_range`中报错：
`    result.append(self.data[cur_index : ptr + 1 - 1] or [self.data[cur_index]])
IndexError: list index out of range`

通过get_length()方法检查过长度是减少了没有问题，但是却还是不成功，请教。

**Comment by IcyW** [comment]
自问自答。
大概是不能这样简单的x.stage，原作者的ClassifierResult类的date列表中，每一个item都是SingleClassifierResult类型的。

**Comment by williamfzc** [comment]
> 前置步骤，auto/start_without_report.py原始脚本的运行很顺利，不过我尝试改cl.load("xxx") 中的图片分类后，通过filter(lambda x: x.stage != '-3', classify_result.data)将非关键帧剔除，并创建新的key_result = ClassifierResult(data=list(key_result_list))

操作有点骚，一般不推荐直接把源数据给改了。

这个问题的原因是这样的：

```python
    def get_stage_range(self) -> typing.List[typing.List[SingleClassifierResult]]:
        """
        return a range list.
        if your video has 30 frames, with 3 stages, this list can be:
        [(0, 1, ... 11), (12, 13 ... 20), (21, 22 ... 30)]

        :return:
        """
```

简单来说就是，ClassifierResult.get_stage_range 需求的数据是连贯的（因为会利用诸如 frame_id 作为索引来切片，这里可能设计得稍微有点耦合，不过暂时是这样的），而你将里面 -3 的东西都去掉了，导致 frame_id 不连续了。

重建 ClassifierResult 是希望达成什么诉求呢？

> 大概是不能这样简单的x.stage，原作者的ClassifierResult类的date列表中，每一个item都是SingleClassifierResult类型的。

你的过滤倒是写得没问题。

**Comment by IcyW** [comment]
感谢神速回复！
操作的确有点骚，差点想直接重构类。过滤掉-3 的frame主要是希望能**用您的draw方法绘图时可以排除无关场景步骤的影响**，直接展示关键帧直接的跳转时延情况。

> ClassifierResult.get_stage_range 需求的数据是连贯的（因为会利用诸如 frame_id 作为索引来切片，这里可能设计得稍微有点耦合，不过暂时是这样的），而你将里面 -3 的东西都去掉了，导致 frame_id 不连续了。

对，刚才我看到这里的注释是第一反应是把去把自定义的图片分类（删去了非关键步骤）中的文件夹名称改成连续的。不过发现这样并不凑效。

**Comment by williamfzc** [comment]
> 操作的确有点骚，差点想直接重构类。过滤掉-3 的frame主要是希望能用您的draw方法绘图时可以排除无关场景步骤的影响，直接展示关键帧直接的跳转时延情况。

实际应用里 -3 存在反而更加重要了，因为它体现了整个视频的变化过程，而这个变化过程目前在我们业务内是比较需要被感知的。
不过我其实还是没太明白你最终想达到一个什么样的业务状态，可以通过 [这里的联系方式](https://github.com/williamfzc/stagesepx#%E5%8F%82%E4%B8%8E%E9%A1%B9%E7%9B%AE) 直接沟通比较快。

**Comment by IcyW** [comment]
> 这里的联系方式

完了，被发现了，一搜索QQ还在同个院群里！
