### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by MannixZ** [williamfzc/work_with_stagesepx#5]
我在使用train_model.py 训练模型的时候, 报错了这个, 应该怎么解决呢? 
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Received a label value of 9 which is outside the valid range of [0, 6).  Label values: 3 3 4 3 4 3 6 0 0 7 4 4 5 2 4 4 1 0 2 0 6 3 9 0 2 1 2 4 8 1 7 3

**Comment by williamfzc** [comment]
https://github.com/williamfzc/stagesepx/issues/112
